### ISSUE TITLE
Launch hiring campaign

### ISSUE THREAD

**Issue by klokan** [maplibre/maplibre#124]
Announce hiring - publish questionary form to collect contact of interested people.

Link the roles.
Mention bounties - for developers.

Message is - this project is stable, we have money to distribute to the community - apply. :-)

**Comment by simonpoole** [comment]
I was causally looking at the "coordinator" role, and given that at least a large part of it would seem to be boring admin/operations type stuff, was left with a lot of boring admin/operations type questions. The type of question you would expect that anybody applying for the role is going to ask, not the least because if venturing in to the minefield it would be good to be prepared.

- the responsibilities list would seem to be rather open ended, enough to fill up a couple of FTEs. Assuming that isn't the intention :-), a rough number of budgeted hours for the position should be given.
- incorporation, what are the plans? There are things that are difficult to do without formal incorporation, would this be part of the role? 
- intellectual property, who owns the intellectual property outside of code contributions? Domain names? Trademarks (I note that MapTiler just registered the CTM for MapLibre)? Is the role supposed to be coordinating this too?
- is there a 2022 budget, 2023?

**Comment by wipfli** [comment]
Thanks for the feedback, @simonpoole!

**Comment by wipfli** [comment]
What is incoorporation?

**Comment by wipfli** [comment]
The budget is, as you might know, a topic which needs discussion. We are still bootstrapping the organization. I expect that we will have a budget for the next quarter by the end of Nov 2022.

**Comment by wipfli** [comment]
Closing the issue because the launch is done. Feel free to follow up though...

**Comment by simonpoole** [comment]
> What is incoorporation?

A typo :-), naturally should be incorporation.
