### ISSUE TITLE
Developer pool total bounties

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#279]
In the developer pool we list how much bounties everybody has earned.

We can update this list once a month after the payments are processed on OpenCollective.

@duje please go though the payments that were made so far and update the pool. Thank you!

**Comment by duje** [comment]
Updated for May, see: https://github.com/maplibre/maplibre/wiki/Developer-Role. Next time: June.

**Comment by birkskyum** [comment]
I think it's worth asking the question, if we should list the total bounties like this, or if we just should keep the list somewhere closer to the quarterly reports if that's it's main use. There is a certain "competitive" vibe around it that I picked up on the other day when told I'm in the "lead" - but I was never trying to be in some sort of race here.

I don't mind it that much, but when the system is expanded to companies at least, it's maybe worth considering if this should be public in the same way, because they might not appreciate it. As an pendant, we'd probably never consider to present historical accumulated list of "total salaries" for our contractors, or "total sponsored funds" near our sponsors.

**Comment by HarelM** [comment]
The open collective expenses are public, I don't think we can or want to change that, I guess this will be applied for companies as well. I guess companies will need to decide if this is something they are willing to entertain in order to get the bounties.

**Comment by birkskyum** [comment]
I'm referring to the tallies in the bounty pool wiki page - no changes to open collective mentioned

**Comment by wipfli** [comment]
OpenCollective shows a sorted list of sponsors here:

![image](https://github.com/maplibre/maplibre/assets/53421382/1235da92-ff70-46db-b988-df741b01f813)

**Comment by wipfli** [comment]
Showing the total paid out amount in the developer pool is useful for us and outside people to understand who are the bounty hunters in MapLibre. This is public information which is available on opencollective, it is just concentrated in this table.

Advantages are:

* If someone wants to pay a developer to implement a feature in MapLibre, they can go to the list and see who did previously do paid work.
* It is a leaderboard and being high on the leaderboard is an additional benefit for people who work on bounties.
* The majority of developers will probably never work on a bounty and get paid out. People who never get active probably should get removed from the pool at some point, and the list helps us with this.

**Comment by birkskyum** [comment]
Thanks for clarifying - I'm glad to learn the intentions for this setup, they do make sense to me
