### ISSUE TITLE
How can there be bounties in a Supported tier?

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre#284]
Supported-tier allow for allocation of paid bounties, but it's not explicit in the [Tiers description](https://github.com/maplibre/maplibre/blob/main/PROJECT_TIERS.md#project-tiers), if that include the cost to have someone manage them.

In a Core-tier project will contracted maintainers control the management of bounties, at the limitation that they themselves can't hunt them. In principle could a volunteer maintainer do the same in a supported project, with the same limitation.

If we entertain the idea of a volunteer driving such a system, should there then be lower expectations for review/response times than there are in the core-tier projects?

If no such volunteer exist, it's hard for me to see how there can be bounties in a supported-tier project at all, unless contracted hours are used. Given how access to bounties is the only difference from hosted projects, this questions the need for having those hosted and supported tiers separated.

**Comment by wipfli** [comment]
Thanks for bringing up this point @birkskyum. I think it is important to have a clear distinction between the supported tier and the core tier. This is given in the current system because only core tier projects get paid maintainer time.

Now to the question who should assign bounties and manage reviews in supported tier projects: I think the management of bounties in the supported tier would have to be done by volunteers, the same way as maintenance is done by volunteers in the supported tier. This approach works if the lead maintainer of a supported tier project is not interested themselves in earning bounties. If however the lead maintainer would like to work on bounties, then we need somebody else to manage the bounties for that project, and that person should then not be earning bounties.

**Comment by birkskyum** [comment]
Sounds good to me.

Just to be clear, I also think the core tier should be clearly separated, so I was more in doubt about the supported and the hosted tier, because they only differ by bounty, and maybe a bit on how we profile the repos.
