### ISSUE TITLE
Onboarding repository maputnik/editor

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre#352]
From: https://github.com/maputnik/editor
To: https://github.com/maplibre/maputnik

## Motivation
Maplibre needs an editor to allow users to edit maps.
When checking with companies who maintain editors and sponsor MapLibre, they said that they are not in a position to open source their editors.
The maintenance effort should not be high as I have done a lot of work to update Maputnik technology stack, and it didn't took a lot of time.

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @nyurik  @birkskyum

## Licensing
- [x] The repo license is MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: <@user>

#### Branches
- [x] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] Repo has a proper GitHub description and an optional web site
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [x] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [x] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by HarelM** [comment]
I don't see a lot of value migrating the other repos:
 - maputnik.github.io can be replaced with the maplibre.org
 - osm-liberty can be replaces with the demo tiles, 
 - desktop can be either be incorporated into the editor or left as a side project that will build separately and not part of the editor repo.
 - design is pretty static and I don't see a lot of value in it, can probably be incorporated if needed as well.
 - maputnik.com is archived
I think "maputnik" will be a better name than "editor" when inside maplibre org.
I'll be helping maintain it going forward.

**Comment by birkskyum** [comment]
I approve of this. It's great to see all the progress made already.

**Comment by wipfli** [comment]
Thank you @HarelM for doing the volunteering to bring Maputnik to the latest MapLibre version and cleaning up things in general. I think it is a good idea to have this project in the MapLibre org

**Comment by HarelM** [comment]
@nyurik I'm leaving this for your care to do all the github migration/transition stuff.
Ping me when it's ready and I'll add all the missing parts that are written here.

Just a side note, Maputnik still doesn't use the latest version of maplibre as I need to publish a new version of the spec, but I believe this won't take long.

**Comment by lseelenbinder** [comment]
I approve, as well! Thanks @HarelM 😄

**Comment by nyurik** [comment]
CCing: @klokan @lukasmartinelli @muesliq @orangemug @oterral @pathmapper @pjsier

**Comment by HarelM** [comment]
While I agree with everything you wrote, I would like to know what is the timeline to this feedback request? As I would like to avoid waiting too long and losing momentum.

Generally speaking, I think maputnik is a great piece of software and I would like to thank everyone who worked on it over the years!

**Comment by nyurik** [comment]
@HarelM no matter what the outcome of this will be, we don't need to loose any momentum.  We can continue doing any kind of innovation of the project (we already have all/most of the rights for that, right?), and in the absolute worst scenario, we will simply rename the project.  So I don't see this as a blocker, but rather as a nice to have (and I agree, it IS nice to have :) )

**Comment by HarelM** [comment]
I, personally, don't have all the relevant permissions, but it's besides the point. 
I would like to have a deadline for this decision please.

**Comment by pathmapper** [comment]
Hello everyone, no objections from my side.

Keep up the good work :-)

**Comment by pjsier** [comment]
This sounds great, thanks for keeping this moving!

**Comment by orangemug** [comment]
This sounds like a great idea. I've been out of the Maputnik project for a while and I'm very happy for my contributions to live on in a new home. Also thanks @nyurik for reaching out

**Idea**: Maybe a few of us could meet at a conference (or virtual) in 2026 for the 10 year anniversary https://www.kickstarter.com/projects/174808720/maputnik-visual-map-editor-for-mapbox-gl/posts/1687628

**Comment by HarelM** [comment]
We have a monthly meeting, next one is on the 10th of January, you are welcome to join :-)
All the information is in our slack channel and the maplibre.org site.

**Comment by klokan** [comment]
Maputnik is a great software tool - which indeed deserves focus and effort from the people who are using it. But what is really stopping interested people in contributing to the code of the tool now - under maputnik github organization - without onboarding it into MapLibre?

First: The project is originally a personal project of @lukasmartinelli - without his permission, I feel like you should not reuse the name of the project and just transfer the repos into MapLibre organization and effectively kill the existing Maputnik github organization and take over. Not without Lukas approval... and as a MapLibre Board Member, I am voting against doing similar things on any project. Original authors deserve credit and rights for the work they did.

Second: I believe that onboarding Maputnik, while I see the benefits for the project and its users, is not really in alignment with the mission and primary goals of MapLibre organization defined in Charter - the formally approved strategy of MapLibre organization - and it may reduce focus and introduce unnecessary tension in the long-term - esp. from operating and promoting live instance of map editor for non-developer end users on maplibre.org.

> Mission: The MapLibre Organization develops free and open-source libraries and tools for mapping that **enable others build applications and services**.

Strategy of organization is defined to have a crystal clear focus - and do very well only a limited number of things - instead of doing everything possible with degraded quality and speed.
At https://github.com/maplibre/maplibre/blob/main/CHARTER.md#maplibre-organization-goals is written the result of (lengthy) discussions and agreement of MapLibre Governing Board approved by Voting Members - for what MapLibre organization goals are, but also what the goals are not:
- MapLibre does not build end-user applications
- MapLibre does not design maps
- MapLibre does not run map hosting services
- MapLibre does not distribute data

Why to set these limits for ourselves at all? Because MapLibre needs focus and wants to develop THE BEST COMPONENTS FOR DEVELOPERS - so that they can work on mentioned things on their own - and cooperate for the benefit of everyone.
We all want open-source mapping components to be technically in parity with Google Maps & Earth or Apple products. The open-source is not there yet. We aim to encourage code development, build a healthy community and stimulate active cooperation between individual developers and commercial vendors - on top of the shared components and tools for developers, which can be used to build end-user products - whether it is done in the open-source contractor ecosystem, in the business/corporate environment, or for personal joy and learning.
Focus and motivation of all involved parties is very important - work on components instead of on end applications to be on safe side - and the open-source model thrive - as there is space for consultants, infrastructure vendors and open-source deploy by power users - all of them can contribute back. If you serve millions of end-users - they will consume the services, but hardly ever contribute back. Open-source projects live from contributions.

Maputnik is "end-user application", it targets primarily designers - not developers. You don't need to be a coder to use it (if it is done well). The users of Maputnik are keen to "design maps". If MapLibre should serve them well - it will need to do everything mentioned above as "don't", including maintaining map designs and possibly also operating map hosting and distributing data. In such case, MapLibre significantly deviates from its mission - and does not hold to the promise given.

Do not fall in the trap of "MapLibre does everything for everybody", what stops you from contributing to the project you love if it is Maputnik - without pushing it into MapLibre? This way we avoid to start to cut the branch we are sitting on with some of the sponsors and motivation of involved parties...

My personal suggestion is to keep the Maputnik tool outside of MapLibre. It deserves its bright future - but in my opinion not inside MapLibre.
If developers need components to build map editors (shared code-base for two editors ideally?) let's design such shared components to encourage cooperation on these, let's focus on making components and tools for developers - to encourage cooperation on code development and code improvement.

Here are my five cents.

**Comment by birkskyum** [comment]
@klokan , thank you for sharing your point of view. Since you didn't mention it yourself, I'll have to point out you have a conflict of interest on this topic through the commercial [MapTiler style editor](https://www.maptiler.com/news/2023/08/design-amazing-maps-with-our-new-style-editor/).

**Comment by zstadler** [comment]
A style editor is a developer's tool.

**Comment by wipfli** [comment]
I think we are in a special situation because actually 3 Board members have a conflict of interest:
- Petr Pridal, because MapTiler has a style editor
- Luke Seelenbinder, because Stadia does not have a style editor
- Harel Mazor, because MapLibre might pay for maintenance in the future.

That said, I think we can as always assume that everybody here argues and acts in the best interest of MapLibre, i.e. in their role as Governing Board members and not in other capacities.

**Comment by louwers** [comment]
> The MapLibre Organization aims to encourage code development. We prefer to empower our users to build end-user applications, design maps, run map hosting services or distribute data rather than making it part of the MapLibre Projects.

The charter says that the MapLibre Organization aims to **empower users to design maps**. It does say that we don't want to make end-user-appllications or map designs part of the MapLibre project. A style editor is an application intended to be used by (map) designers, and those are not end-users. While I agree with @klokan that keeping the focus of the project is very importent, in my reading of the charter Maputnik is definitely in scope.

Do any of the board members recurse themselves from voting on this based on conflict of interest?

**Comment by HarelM** [comment]
I don't mind recusing myself if this is what's needed here.
It's worth noting that even if Maputnik will be transferred under the Maplibre org, it will be in the "hosted" project tier, which means MapLibre will not pay for neither bounties nor maintenance.
Only a core project get maintainers' resources, and in order for a project to be moved from hosted tier to core/supported there's another vote that needs to be approved by the board.
See here: https://github.com/maplibre/maplibre/blob/main/PROJECT_TIERS.md
And even if this vote is passed, there's still a process of either setting of bounties, which I don't do in most cases in order to let more community member participate, or selecting a maintainer, which might not even be me (It might be better to have one of the original maintainers maintain this, if they are available, for example).

But, if someone feels that my motivation isn't for the greater good of MapLibre, and I get why someone might feel this way, I'm good with recusing myself, honestly, no harm is done, no hard feelings. :-)

I also opened this on boarding ticket to avoid the need to vote myself, just in case.

So I guess it's mainly up to you @birkskyum & @nyurik.

**Comment by nyurik** [comment]
Thanks everyone for the feedback.  I understand this is not a simple issue, so let me add my 2- before-inflation-cents.

### Name Ownership
@klokan brings a valid point about the name and who owns it, but I don't think it is as clean cut as Lukas simply owning it and noone else has any rights to it.  IANAL, and my non-legal reasoning is that the project (active members / admins / ...) are the people who jointly own the name as long as the name continues to represent the original project goals.  This is exactly why Lukas granted project adminship to several people - to help it grow and to manage its future. If the majority of the project active maintainers want to continue under the same name, it will only benefit everyone. Splitting the community just for the sake of a name is not a good idea, especially when the new maintainers have the same goals in mind as the original authors.

Lastly, Maputnik is NOT trademarked at the moment (I did a quick search in European and US registries), and unless someone decides to quietly squat it, its ownership is best left to those interested in maintaining the project.  Going forward, it **might** be a good idea to trademark, but lets keep that as a separate debate.

### MapLibre Alignment
Clearly, Maputnik is a tool relevant almost exclusively to the MapLibre's ecosystem.  There is a big separation between offering a service vs maintaining code, but the separation between "code" developers and "design" developers (styling rules) brought up by @klokan is artificial at best.  Both are often implemented by the same person. Let's not split hairs here. The tooling is clearly within the scope of MapLibre per @klokan's own post:  "Mission: The MapLibre Organization develops free and open-source libraries and **tools** for mapping that enable others build applications and services." (emphasis is mine). Moreover, I do believe we should make Maputnik easier to use as a library component - so that anyone can easy include it into their own application.

### Conflict of Interest
There are different types of conflicts.  Most of the mapping community is interested in getting a well supported and maintained editor. Obviously, anyone using Maputnik would be benefiting financially because they won't have to implement it themselves -- in my mind, this is not a conflict because otherwise any corporate FOSS participation is a conflict. Furthermore, student participation is a conflict because they get learning experience and future potential for a job as a resume references...  absurd, I know.

A conflict would be if the Maputnik maintainer is expecting financial compensation from MapLibre org and votes for Maputnik.  Another conflict would be if the person is financially benefiting from a competing product, and is voting against Maputnik. Both may be perceived as not acting in the best interests of the project.

Please remember that the board members must **ONLY** vote in the best interest of the **MapLibre** project itself, and **nothing** else.  If the individual is not able to do so, or if they are perceived by many as having a conflict, they should abstain from voting.  If the individual is not able to do so, they should not be on the board.

I do think the discussion so far has focused on what's best for MapLibre, and the board members were not thinking of outside interests.  Disagreements are normal, and I think we should be able to resolve them without resorting to accusations of conflicts of interest.

### Next Steps
Apart from Peter's concerns, which I fully understand but disagree with per above, I think we have a general agreement over this.  I would like to wait for @lukasmartinelli to chime in for another week, and unless he has a strong objection, I would like to move forward with the migration.

**Comment by muesliq** [comment]
I share @klokan's feeling that it wouldn't feel okay to onboard Maputnik without @lukasmartinelli's approval. And I want to share a perspective to Petr's second point: 

We ([Maptoolkit](https://www.maptoolkit.com/)) have contributed financially to Maputnik's initial development. However we later realised that the GUI approach is inferior in speed and flexibility to a source code approach. Therefor we built our own Style Editor that follows a JSON editor approach with many GL specific features, debugging and batch editing tools and error checks.

I agree with Petr that Maputnik is not an ideal tool for developers. It has a lower learning curve that code based editors but is not the ideal tool for savvy users. 

![image](https://github.com/maplibre/maplibre/assets/1606618/40c2e60b-adac-4135-8116-4eb3932456cd)

**Comment by HarelM** [comment]
>We ([Maptoolkit](https://www.maptoolkit.com/)) have contributed financially to Maputnik's initial development. However we later realised that the GUI approach is inferior...

This actually proves that at some point you considered Maputnik as a tool to allow you to build your services: static maps, routing, elevation, etc... (quoting your site API offering)
Sure, it might not be perfect, but as I wrote earlier, no company has stepped forward and suggested to open source their tool, and we all know there are map editing tools out there that are in use internally (which is totally fine BTW).

**Comment by muesliq** [comment]
True.

We discussed internally offering our editor to be open-sourced. To be honest we shy away from the effort this entails, cleaning up code, documenting, etc. We don't really have time for that at the moment.

**Comment by zstadler** [comment]
Theoretically, of course, had you decided to open-source the project, wouldn't you prefer that an organization like MapLibre would onboard it rather than not?

**Comment by muesliq** [comment]
Sure but that doesn't necessarily mean that Maputnik is the right fit for MapLibre.

**Comment by zstadler** [comment]
The problem Maputnik addresses is well within the scope of the MapLibre organization and the needs of the community it serves.
We're not faced with a dilemma of choosing between Maputnik and another open-source project for this need...

**Comment by birkskyum** [comment]
I'm supportive of keeping Maputnik afloat under the MapLibre umbrella, because as a satellite project it had recently lost compatibility with latest maplibre-gl/maplibre-styl-spec versions which felt quite unsatisfactory. For good or bad I think it does provide value to the community to have an OSS editor available, even with various superior proprietary editors around that integrate more tightly with other customer data. I don't see any open alternatives to it at present, but if an objectively better editor eventually do open source, that would be just be amazing for the community, and I can easily imagine it would steal the community support and thunder.

**Comment by wipfli** [comment]
@muesliq is your main concern that Maputnik is not a good map style editor?

Or is your main concern that the name "Maputnik" should not be used and instead we should fork it and give it a new name?

**Comment by wipfli** [comment]
Feel free to join the monthly meeting today 8 PM to 9 PM CET @muesliq. The link is in our slack channel.

**Comment by muesliq** [comment]
> @muesliq is your main concern that Maputnik is not a good map style editor?
> 
> Or is your main concern that the name "Maputnik" should not be used and instead we should fork it and give it a new name?

I voiced two concerns (similar to @klokan):

1. Lukas should give his OK to onboarding. (And I imagine he will.)
2. Maputnik is not the best possible fit for MapLibre for the reasons outlined. (I am undecided if it is better for MapLibre to have no editor at all or Maputnik.) 

Would join tonight but I don't have time unfortunately.

**Comment by nyurik** [comment]
@lukasmartinelli has emailed me his support for the on-boarding:

![image](https://github.com/maplibre/maplibre/assets/1641515/c12185b4-1964-44ed-96fd-c8ae067745c0)

**Comment by jsehner** [comment]
The development of the really great Maputnik Editor is stumbling since 2020, users worried about extinction. MapLibre developers brought it back to life and spread new hopes. So all Maputnik users would be probably happy about an onboarding into MapLibre.

**Comment by HarelM** [comment]
I've opened the above PR to resolve the missing files and content.
@nyurik @birkskyum I listed you as the approvers for this migration request in the initial post.
I'm not aware of anything else preventing this from getting migrated.
@nyurik I leave the rest to you. :-)

**Comment by nyurik** [comment]
Repository has been moved as `maplibre/maputnik`, but the rest of the related repos was kept in place. I wonder if we should somehow move the other repos, or perhaps consolidate them into a monorepo?

We **might** want to move the editor demo site and/or other things?

**Comment by HarelM** [comment]
Great! Thanks!
Regarding the other repos, see my comment above:
https://github.com/maplibre/maplibre/issues/352#issuecomment-1873319489

**Comment by nyurik** [comment]
From https://github.com/maplibre/maplibre/issues/352#issuecomment-1873319489 :

> * maputnik.github.io can be replaced with the maplibre.org
> * osm-liberty can be replaces with the demo tiles,
> * desktop can be either be incorporated into the editor or left as a side project that will build separately and not part of the editor repo.
> * design is pretty static and I don't see a lot of value in it, can probably be incorporated if needed as well.

I do think desktop should be merged into maplibre and archived. I pinged @kevinschaul in https://github.com/maputnik/desktop/pull/18#issuecomment-1887824544 as they might have some insight into doing taht.

**Comment by wipfli** [comment]
Can this be closed @HarelM ?

**Comment by nyurik** [comment]
@wipfli could you do the twitter announcement?  This news has already been suggested for the newsletter, and I did mention it on slack - so that pretty much covers all of it.

We do have several non-board members with maintainer access.  I wonder if the "admin" right is ever needed?

Lastly, npmjs access is not available because we have no way of contacting whoever published it initially. I started a process with github, but that might take some time.

**Comment by wipfli** [comment]
Sounds good to me. Will add Maputnik to the next newsletter.

**Comment by zstadler** [comment]
> Lastly, npmjs access is not available because we have no way of contacting whoever published it initially.

I think we have good chances of reclaiming the package name thru a [dispute resolution](https://docs.npmjs.com/policies/disputes)

- The package was [published just once](https://www.npmjs.com/package/maputnik/v/1.2.0?activeTab=versions), in version 1.2.0, 6 years now, in version 1.2.0.
- The package was published from the [github.com/maputnik/editor](https://github.com/maputnik/editor) repository, which was not owned by the publisher
- The owners of the original repository approved its on-boarding to MapLibre

**Comment by nyurik** [comment]
Yep,  that's the process I'm following. It has been a few weeks now, no response yet

**Comment by HarelM** [comment]
It might be easier to simply publish a new one called `@maplibre/maputnik` I guess. It will also affiliate maputnik with maplibre this way.
In general, I think we agreed new packages will be named with `@maplibre/` prefix, and if the above was not publishe for 6 years I'll be surprized if anyone actually uses it.

**Comment by zstadler** [comment]
> I'll be surprized if anyone actually uses it.

FWTW, there were about 3 downloads/week in the past year.
![image](https://github.com/maplibre/maplibre/assets/1304610/a732b5ec-ad52-43f2-bbeb-f15c58affd4a)

**Comment by nyurik** [comment]
Tbh, I would prefer to keep root name for continuity and to reduce confusion in the future.  Buy I do understand the need to publish... perhaps we should try to poke Microsoft contacts to speed it up?
