### ISSUE TITLE
State and future of maplibre-rs

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre#424]
Hi everyone! Sadly I won't make it to the next  native meeting. However, I wanted to raise a discussion about maplibre-rs and what the board & project coordination thinks about the project.

I'm currently in the process of translating about 10k lines of C++ to Rust and reached a POC state where I can use SDF font rendering (as designed in maplibre-native) in maplibre-rs.

However, I fear that without investing actual money/resources into the project beyong my capabilities the project won't be sustainable and it might be more realistic to return to the projects origins where it is just a project that brings joy to me without following the vision of becoming a useful part of the MapLibre ecosystem. That would mean essentially removing the "MapLibre" branding of maplibre-rs.

I think its the right time to discuss the fait of the project now with the new project coordination in place.

Note that the above is not really meant as a public discussion but more as a request to the board & tech. coordination to draft a vision for maplibre-rs.

You might call this a request for a board opinion.

**Comment by birkskyum** [comment]
The board received your asssesment that maplibre-rs only would be sustainable if the board could funnel resources into it:

> 12th Nov - Max Ammann: I fear that without investing actual money/resources into the project beyong my capabilities the project won't be sustainable
> 15th Nov - Max Ammann: it seems like it might make more sense to abandon the project if the board is not backing the project.
 
We started compiling material to better understand this inquiry, educating ourselves on the topic, scheduling discussion meetings etc., so that we can evaluate your request and find ways to provide the project the necessary backing you ask.

You then provided us a more specific suggestion for how this work could take shape. To modularize the renderer and create Rust libraries under the MapLibre umbrella that can be funded:

> 15th Nov - Max Ammann: Idea related to the above discussion: Maybe it could make sense to create Rust libraries under the MapLibre umbrella that e.g. implement SDF font rendering (90% done right now). Those could then be used by maplibre-native in the future.

The board offered to put your suggestion on the agenda of our [quarterly board meeting](https://osmus.slack.com/archives/C01G3D28DAB/p1731676249768199?thread_ts=1731671419.296779&cid=C01G3D28DAB), 19th Nov, to expedite a funding decision. For your suggestion to be feasible, we would naturally also have to ensure this is desirable for the MapLibre Native renderer:

> 15th Nov - Birk Skyum: I believe maplibre could support financially within the existing sponsorship program.
> [..] We have a board meeting Tuesday, and they’re typically quite packed, but if possible this would be good to have on the agenda too ( cc ramyaragupathy )

This effort was [declined](https://osmus.slack.com/archives/C01G3D28DAB/p1731688725675049?thread_ts=1731671419.296779&cid=C01G3D28DAB), when you clarified that you're **not looking for funding**:

> 15th Nov - Max Ammann: I'm not really looking for funding as that is not really what would motivate me to keep going. 

The language of backing/resources/investing/money seemed central to this issue, so if there's no concern of funds, let's leave that out. I think's better to open a "Discussion" instead, since there's no clear action point.

**The vision for maplibre-rs** - The project vision is driven by the people working on it, the maintainers and community, rather than the board. The exception to this rule is when funds are spent, because then it's the boards responsibility to make sure the money are put to good use. Being a bottom-up organization, rather than top-down, means that plans for, and development,  of martin, maplibre-react-native, maputnik isn't controlled by maplibre, we merely Host the projects, as an umbrella for FOSS mapping libraries.

We'd be happy to share our opinion on your vision for the project. Due to the org being driven bottom-up, and largely by voluntary contributions, it's best that it's that way around, and not the other, since it could be demotivating if the board put forward a vision for a project, that's not aligned to the motivations of the contributors of it.

For further inquiries to the board, please note that we're all governing MapLibre on a voluntary basis, and that we're all having significant responsibilities next to that, and thus have limited availability, so specific are good.

Thanks.

**Comment by maxammann** [comment]
> For further inquiries to the board, please note that we're all governing MapLibre on a voluntary basis, and that we're all having significant responsibilities next to that, and thus have limited availability - so the more specific the better.

I'm sorry if my request caused any friction or stress. I was unsure which process to follow to ask about the board's opinion as the #maplibre channels is mostly used for MapLibre support or project presentations. After some thought I came to the conclusion that this GH project is likely the best way of communication.


> The vision for maplibre-rs
> The project vision is generally driven by the people working on it, the maintainers and community, being a bottom-up organization - with the board mainly touching projects when it comes to onboarding, funding etc..

This makes a lot of sense. I feel what's lacking for maplibre-rs is a community and multiple maintainers. As I failed to achive that thorough the years I feel like it would make sense to offboard maplibre-rs from MapLibre. Even thorugh the project has been idling a lot in the past 2 years I always intended to invest as much time as I can into the project and I would love to continue doing that. However, sharing the name "MapLibre" seems inappropriate to me by now. It seems like vision for maplibre-rs "one code to rule them all" is not/no longer ubiquously shared between MapLibre project maintainers.

Therefore, such that I pesonally still have fun driving the "Rust map renderer project" forward the best option is to change the name of the project from maplibre-rs so something else (let's use maps-rs in the meantime) and transfer the project back to my personal GitHub account.

Let me know what you think and if that path forward is acceptable to you! Thanks for all the resources and support I received in the past years! Definitely looking forward to meet the community again at the next State of the Map or similar.

**Comment by birkskyum** [comment]
@maxammann The suggestion you have to off-board the project, and then strip if of references to maplibre - it sounds like a quite destructive action, that would break the association/links to the published academic work, scopes and docs, that _did_ aim to be a "unifying renderer" written in rust, and these other places:

- https://web.archive.org/web/20220807144111id_/https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLVIII-4-W1-2022/35/2022/isprs-archives-XLVIII-4-W1-2022-35-2022.pdf
- https://www.youtube.com/watch?v=Qq4cj0kfOUE
- https://crates.io/crates/maplibre
- https://maplibre.org/maplibre-rs/docs/book/
- https://webgl.demo.maplibre-rs.maplibre.org/

Have you considered simply forking it? Keeping "maplibre-rs" in place, with all the associations to it, could make it easier to  dissociate a new technical direction from that name. That is likely less confusing than having maplibre-rs redirect to a project that completely abandons its original promise.

You'd basically, in a non-destructive way, be free to do all the things you mention:
- Rename, away from maplibre
- Have project under personal scope
- Refactor at will
- Present new technical direction and goals

**Comment by maxammann** [comment]
>  did aim to be a "unifying renderer" written in rust

Unfortunately, I don't see that vision becoming reality. That did not happen the past 3 years. The project barely received any outside contributions - none that actually drove the project forward.

I'd like to keep the whole repository history in one place, under my personal account. Having all the issues, including potential watching collaborators is essential for me.

I'm going to makre sure that the impact will be limited. I think the only links that might break is the maplibre.org link: https://maplibre.org/maplibre-rs/docs/book/

However it would be trival to continue publishing to that URL. I could leave there a note saying that the project is no longer. When transferring a GH repository all links to code or issues should remain intact at https://github.com/maplibre/maplibre-rs
GitHub should forward all requests to the transferred repository. If that does not turn out to be the case then I can recreate the maplibre-rs repository after the transfer with documentation about the state and reuslts of the maplibre-rs experiement.

**Comment by birkskyum** [comment]
> I'd like to keep the whole repository history in one place, under my personal account. 

When the project was onboarded, you were the sole author and copyright holder. Now there are 18 community members that have contributed, and the copyright is owned by the MapLibre Contributors. Therefore it's a challenge for the board to simply transfer back all the rights to the repo to your personal account at this point, several years down the road. My recommendation would be to either make a fork of the project if you want to take it a completely different way OR to lean into the amazing MapLibre Community [who's excited for you and for maplibre-rs](https://osmus.slack.com/archives/C03BW73DJBH/p1732058110763569).
